server:
  port: 8087


### r2dbc
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test #?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    #url: r2dbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root  #root postgres
    password: 123456
    #pool: # 不能配置连接池会出问题，一直掉链接
      #enabled: true
      #max-size: 10
      #initial-size: 5
      #validation-query: select 1
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/vue-blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: 123456
easyorm:
  auto-ddl: true
  default-schema: test     # 默认使用的schema. mysql时则为数据库名
  dialect: mysql # 方言: h2,mysql,postgres



logging:
  level:
    org.springframework.r2dbc: DEBUG  #输出执行的sql
    org.hswebframework: debug
    org.hswebframework.expands: error

hsweb:
  webflux:
    response-wrapper:
      enabled: true # 将响应结果包装为{"status":200,"result":{}}
      excludes: #不包装的类
        - org.springdoc